#!/bin/bash
# Generates a .gs file with a prepackaged set of closed/merged GitHub issues and PRs.
# Uses the GitHub CLI (gh) to query repos from the last 2 years.
# Output format: { "org/repo": { merged: [1,2,3], closed: [4,5,6] }, ... }

set -euo pipefail

REPOS=(
  "kubernetes/kubernetes"
  "kubernetes-sigs/wg-serving"
  "kubernetes/enhancements"
  "kubernetes-sigs/inference-perf"
  "kubernetes/test-infra"
  "kubernetes-sigs/cri-tools"
  "google/cadvisor"
  "kubernetes/node-problem-detector"
  "kubernetes/community"
  "kubernetes/cloud-provider-gcp"
  "kubernetes/website"
  "GoogleCloudPlatform/k8s-node-tools"
)

SINCE=$(date -v-2y +%Y-%m-%dT00:00:00Z 2>/dev/null || date -d '2 years ago' +%Y-%m-%dT00:00:00Z)
OUTPUT="src/closed-data.gs"

echo "Fetching closed/merged issues and PRs since $SINCE..."
echo "This may take a few minutes."
echo ""

total=0

cat > "$OUTPUT" << 'HEADER'
/**
 * AUTO-GENERATED — do not edit manually.
 * Generated by generate-closed-data.sh
 *
 * Format: { "org/repo": { merged: [numbers], closed: [numbers] } }
 * Used to label old email threads for issues/PRs that are now closed or merged.
 */
const CLOSED_ITEMS = {
HEADER

first_repo=true

for repo in "${REPOS[@]}"; do
  echo "Processing $repo..."

  merged_nums=""
  closed_nums=""

  # Closed issues
  issue_count=0
  while read -r number; do
    [ -z "$number" ] && continue
    closed_nums="${closed_nums:+$closed_nums,}$number"
    issue_count=$((issue_count + 1))
  done < <(gh issue list --repo "$repo" --state closed --limit 5000 \
    --search "closed:>=$SINCE" --json number --jq '.[].number' 2>/dev/null || true)
  echo "  Issues closed: $issue_count"
  [ "$issue_count" -ge 5000 ] && echo "  WARNING: issue results hit the 5000 cap; older items may be missing."

  # Closed/merged PRs
  merged_count=0
  closed_pr_count=0
  while IFS=$'\t' read -r number state; do
    [ -z "$number" ] && continue
    if [ "$state" = "MERGED" ]; then
      merged_nums="${merged_nums:+$merged_nums,}$number"
      merged_count=$((merged_count + 1))
    else
      closed_nums="${closed_nums:+$closed_nums,}$number"
      closed_pr_count=$((closed_pr_count + 1))
    fi
  done < <(gh pr list --repo "$repo" --state closed --limit 5000 \
    --search "closed:>=$SINCE" --json number,state --jq '.[] | [.number, .state] | @tsv' 2>/dev/null || true)
  echo "  PRs merged: $merged_count, closed: $closed_pr_count"
  [ "$((merged_count + closed_pr_count))" -ge 5000 ] && echo "  WARNING: PR results hit the 5000 cap; older items may be missing."

  repo_total=$((issue_count + merged_count + closed_pr_count))
  total=$((total + repo_total))

  # Skip repos with no data
  if [ $repo_total -eq 0 ]; then
    echo "  Skipped (no data)"
    echo ""
    continue
  fi

  if [ "$first_repo" = true ]; then
    first_repo=false
  else
    echo "," >> "$OUTPUT"
  fi

  echo -n "  \"$repo\": {merged:[${merged_nums}],closed:[${closed_nums}]}" >> "$OUTPUT"
  echo ""
done

echo "" >> "$OUTPUT"
echo "};" >> "$OUTPUT"

echo "Total items: $total"
echo "Generated $OUTPUT"
ls -lh "$OUTPUT"
echo "Run 'make push' to deploy."
